[server]
# Mengatur batas maksimal upload file (dalam Megabyte) agar RAM tidak sesak
maxUploadSize = 10
# Mematikan pengiriman data telemetri penggunaan ke Streamlit
gatherUsageStats = false

[theme]
primaryColor = "#4F5666"
backgroundColor = "#F9F9FB"
secondaryBackgroundColor = "#E6DDD4"
textColor = "#2D3748"